### ISSUE TITLE
Inquiry Regarding Privacy Compliance

### ISSUE THREAD

**Issue by raheel-sadiq-zalando** [warrenm/DracoSwift#1]
I hope this message finds you well. I'm currently using your library DracoSwift in my iOS application, and I'm seeking clarification regarding its privacy implications.

As part of Apple's requirement for iOS applications, it's essential to ensure compliance with privacy guidelines and to be transparent with users about any data collection or usage. Thus, I'd like to inquire about whether DracoSwift collects any user data or accesses sensitive user information.
More info: [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)

**Request for Clarification:**
Could you please provide clarification on the any privacy implications of using DracoSwift. Any insights or guidance you can offer would be greatly appreciated.

Thank you for your attention to this matter. I look forward to your response.

**Comment by warrenm** [comment]
Thanks for the question. DracoSwift does not—and will not ever—collect any user data whatsoever, nor does it make any outbound HTTP requests. It is compiled directly from the official source provided by Google, which is readily available online (and is linked from the project README).

I’m happy to address any remaining concerns you might have.
